version: '3.3'
services:
  # Backend
  shroomish-backend:
    image: shroomish-backend
    container_name: shroomish-backend
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - shroomish
    ports:
      - 8080:8080
    volumes:
      - './backend:/home/node/app'
      - '/home/node/app/node_modules'
  # # Classifier
  shroomish-classifier:
     image: shroomish-classifier
     container_name: shroomish-classifier
     build:
       context: classifier
       dockerfile: Dockerfile
     restart: always
     networks:
       - shroomish
     ports:
       - 5000:5000

  # DB
  shroomish-db:
    image: shroomish-db
    container_name: shroomish-db
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    networks:
      - shroomish
    ports:
      - 5432:5432

  # Client
  shroomish-client:
        image: shroomish-client
        container_name: shroomish-client
        build:
          context: frontend
          dockerfile: Dockerfile
        volumes:
          - './frontend:/usr/src/app'
          - '/usr/src/app/node_modules'
        ports:
          - 3000:3000
        restart: always

  #Client prod
  #client-prod:
  #  container_name: client-prod
  #  build:
  #    context: frontend
  #    dockerfile: Dockerfile-prod
  #  ports:
  #    - '80:80'

#Shroomish network
networks:
  shroomish:
    external:
      name: shroomish
